version: '3.8'

services:
  database:
    container_name: oo-database
    image: postgres:alpine
    environment:
      - POSTGRES_USER=openobservatory
      - POSTGRES_PASSWORD=openobservatory
      - POSTGRES_DB=openobservatory
    volumes:
      - data:/var/lib/postgresql/data
  backend:
    container_name: oo-backend
    depends_on:
      - database
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/openobservatory
      - SPRING_DATASOURCE_USERNAME=openobservatory
      - SPRING_DATASOURCE_PASSWORD=openobservatory
  frontend:
    container_name: oo-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "8080:80"

volumes:
  data:
