name: Backend - Continuous Integration

on:
  pull_request:
    paths:
      - gradle/**
      - src/**
      - build.gradle
      - settings.gradle
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths:
      - gradle/**
      - src/**
      - build.gradle
      - settings.gradle

jobs:
  lint:
    name: Backend - Lint phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew spotlessCheck

  test:
    name: Backend - Test phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew test

  build:
    needs: test
    name: Backend - Build phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew build
