name: Docker

on:
  push:
    branches:
      - develop
      - main

jobs:
  backend:
    name: Backend - Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/openobservatoryteam/open-observatory-backend:${{ github.sha }} -t ghcr.io/openobservatoryteam/open-observatory-backend:latest .
      - run: docker push -a ghcr.io/openobservatoryteam/open-observatory-backend

  frontend:
    name: Frontend - Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/openobservatoryteam/open-observatory-frontend:${{ github.sha }} -t ghcr.io/openobservatoryteam/open-observatory-frontend:latest ./frontend
      - run: docker push -a ghcr.io/openobservatoryteam/open-observatory-frontend
