name: Frontend - Continuous Integration

on:
  pull_request:
    paths:
      - frontend/**
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
    paths:
      - frontend/**

jobs:
  lint:
    name: Frontend - Lint phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: pnpm/action-setup@v2
        with:
          version: '7'
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
          node-version: '18'
      - run: pnpm install
        working-directory: frontend
      - run: pnpm lint
        working-directory: frontend

  build:
    name: Frontend - Build phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: pnpm/action-setup@v2
        with:
          version: '7'
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
          node-version: '18'
      - run: pnpm install
        working-directory: frontend
      - run: pnpm build
        working-directory: frontend

  frontend:
    name: Frontend - Sonar analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./frontend
