name: Sonar analysis

on:
  pull_request:
    paths:
      - frontend/**
      - gradle/**
      - src/**
      - build.gradle
      - settings.gradle
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - develop
      - main
    paths:
      - frontend/**
      - src/**
  schedule:
    - cron: '0 2 * * *'

jobs:
  backend:
    name: Backend - Sonar analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew build sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  frontend:
    name: Frontend - Sonar analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./frontend
